language: r
cache: packages

r:
  - release

jobs:
  include:
    - os: linux
    - os: osx
      osx_image: beta-xcode6.1
      disable_homebrew: true
  
env:
  - _R_CHECK_TESTS_NLINES_=0
  
script:
  - |
    R CMD build .
    R CMD check --no-build-vignettes --no-manual --as-cran *tar.gz
  