language: r
cache: packages

r:
  - release

os:
  - linux
  
env:
  - _R_CHECK_TESTS_NLINES_=0
  
script:
  - |
    R CMD build .
    R CMD check --no-build-vignettes --no-manual --as-cran *tar.gz
  